#!/bin/bash

dataset_dir="../../datasets/CUB_200_2011_wTEXT"
trainclasses_fn="trainclasses.txt"
valclasses_fn="valclasses.txt"
testclasses_fn="testclasses.txt"
image_dir="image_embs_h5"
text_dir="captions"
text_cutoff="201"
level="char"
vocab_fn="vocab_c10.t7"
conv_channels_ar=("100 150 200" "312 514 256")
conv_kernels_ar=("3 3 3" "5 5 5" "7 7 7")
conv_strides_ar=("3 3 3" "4 4 4")
rnn_num_layers="2"
rnn_bidir_ar=("" "-rb")
lstm_ar=("" "--lstm")
conv_dropout_ar="0. 0.05"
rnn_dropout_ar="0.1 0.3"
lin_dropout_ar="0.1 0.3"
batches="30000"
learning_rate_ar="0.0007 0.0001 0.00001"
lr_decay_ar=("" "-lrd")
model_dir="models"
summary="models/experiments.txt"
device="cuda:0"

for conv_channels in "${conv_channels_ar[@]}"; do
for conv_kernels in "${conv_kernels_ar[@]}"; do
for conv_strides in "${conv_strides_ar[@]}"; do
for rnn_bidir in "${rnn_bidir_ar[@]}"; do
for lstm in $lstm_ar; do
for conv_dropout in $conv_dropout_ar; do
for rnn_dropout in $rnn_dropout_ar; do
for lin_dropout in $lin_dropout_ar; do
for learning_rate in $learning_rate_ar; do
for lr_decay in "${lr_decay_ar[@]}"; do
    echo "Training -ch $conv_channels -k $conv_kernels -cs $conv_strides" \
    "$lstm $rnn_bidir -lr $learning_rate $lr_decay"

    python text2image/train_text_encoder.py -d $dataset_dir \
    -avc $trainclasses_fn -i $image_dir -t $text_dir \
    -cut $text_cutoff -lvl $level -v $vocab_fn -ch $conv_channels \
    -k $conv_kernels -cs $conv_strides -rn $rnn_num_layers $rnn_bidir \
    $lstm -ld $lin_dropout -cd $conv_dropout -rd $rnn_dropout -b $batches \
    -lr $learning_rate $lr_decay -md $model_dir -dev $device -pe 50

    echo "Evaluating on validation -ch $conv_channels -k $conv_kernels" \
    "-cs $conv_strides $lstm $rnn_bidir -lr $learning_rate $lr_decay"

    python text2image/evaluate_text_encoder.py -d $dataset_dir \
    -avc $valclasses_fn -i $image_dir -t $text_dir \
    -cut $text_cutoff -lvl $level -v $vocab_fn -ch $conv_channels \
    -k $conv_kernels -cs $conv_strides -rn $rnn_num_layers $rnn_bidir \
    $lstm -cd $conv_dropout -rd $rnn_dropout -ld $lin_dropout -b $batches \
    -lr $learning_rate $lr_decay -md $model_dir -s $summary -dev $device
done
done
done
done
done
done
done
done

echo "Evaluating best model on test"

python text2image/evaluate_best_text_encoder.py -d $dataset_dir \
-avc $testclasses_fn -i $image_dir -t $text_dir -cut $text_cutoff \
-v $vocab_fn -md $model_dir -dev $device -s $summary -c